"""esquema inicial

Revision ID: 97018f99ef86
Revises: 
Create Date: 2026-07-12 10:29:12.237650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97018f99ef86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = ('business',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ruc', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('estado_ruc', sa.Enum('ACTIVO', 'SUSPENDIDO', name='estadoruc'), nullable=False),
    sa.Column('datos_kyc', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_ruc'), ['ruc'], unique=True)

    op.create_table('nota_credito',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero_autorizacion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ruc_beneficiario', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('valor_nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_disponible', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('NCD', 'NCD_ISD', name='tiponotacredito'), nullable=False),
    sa.Column('historial_endosos', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nota_credito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nota_credito_numero_autorizacion'), ['numero_autorizacion'], unique=True)
        batch_op.create_index(batch_op.f('ix_nota_credito_ruc_beneficiario'), ['ruc_beneficiario'], unique=False)

    op.create_table('expediente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('nota_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('RECIBIDO', 'EN_VALIDACION', 'PENDIENTE_DOCUMENTACION', 'LISTO_PARA_NEGOCIAR', 'EN_NEGOCIACION', 'CERRADO', 'RECHAZADO', 'CANCELADO', name='estadoexpediente'), nullable=False),
    sa.Column('monto_a_negociar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('responsable', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['nota_id'], ['nota_credito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expediente_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_nota_id'), ['nota_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_expediente_responsable'), ['responsable'], unique=False)

    op.create_table('documento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expediente_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('CEDULA', 'PAPELETA', 'CERTIFICADO', 'PLANILLA', 'KYC', 'CESION', 'NOTA', name='tipodocumento'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('hash_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expediente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expediente_id', 'tipo', 'version', name='uq_documento_expediente_tipo_version')
    )
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documento_es_activo'), ['es_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_expediente_id'), ['expediente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_hash_sha256'), ['hash_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_tipo'), ['tipo'], unique=False)

    op.create_table('historial_estados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expediente_id', sa.Uuid(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('RECIBIDO', 'EN_VALIDACION', 'PENDIENTE_DOCUMENTACION', 'LISTO_PARA_NEGOCIAR', 'EN_NEGOCIACION', 'CERRADO', 'RECHAZADO', 'CANCELADO', name='estadoexpediente'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('RECIBIDO', 'EN_VALIDACION', 'PENDIENTE_DOCUMENTACION', 'LISTO_PARA_NEGOCIAR', 'EN_NEGOCIACION', 'CERRADO', 'RECHAZADO', 'CANCELADO', name='estadoexpediente'), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expediente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_estados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_estados_expediente_id'), ['expediente_id'], unique=False)

    op.create_table('riesgo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expediente_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('nivel', sa.Enum('CRITICO', 'ALTO', 'MEDIO', 'BAJO', name='nivelriesgo'), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'RESUELTO', name='estadoriesgo'), nullable=False),
    sa.Column('evidencia', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expediente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riesgo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riesgo_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_riesgo_expediente_id'), ['expediente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_riesgo_nivel'), ['nivel'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riesgo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riesgo_nivel'))
        batch_op.drop_index(batch_op.f('ix_riesgo_expediente_id'))
        batch_op.drop_index(batch_op.f('ix_riesgo_estado'))

    op.drop_table('riesgo')
    with op.batch_alter_table('historial_estados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_estados_expediente_id'))

    op.drop_table('historial_estados')
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_tipo'))
        batch_op.drop_index(batch_op.f('ix_documento_hash_sha256'))
        batch_op.drop_index(batch_op.f('ix_documento_expediente_id'))
        batch_op.drop_index(batch_op.f('ix_documento_es_activo'))

    op.drop_table('documento')
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expediente_responsable'))
        batch_op.drop_index(batch_op.f('ix_expediente_nota_id'))
        batch_op.drop_index(batch_op.f('ix_expediente_estado'))
        batch_op.drop_index(batch_op.f('ix_expediente_cliente_id'))

    op.drop_table('expediente')
    with op.batch_alter_table('nota_credito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nota_credito_ruc_beneficiario'))
        batch_op.drop_index(batch_op.f('ix_nota_credito_numero_autorizacion'))

    op.drop_table('nota_credito')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_ruc'))

    op.drop_table('cliente')
    # ### end Alembic commands ###
