"""nota_credito 1 a muchos expedientes

Revision ID: c63eed84bf60
Revises: 97018f99ef86
Create Date: 2026-07-12 11:29:26.152395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c63eed84bf60'
down_revision: Union[str, Sequence[str], None] = '97018f99ef86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expediente_nota_id'))
        batch_op.create_index(batch_op.f('ix_expediente_nota_id'), ['nota_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expediente_nota_id'))
        batch_op.create_index(batch_op.f('ix_expediente_nota_id'), ['nota_id'], unique=1)

    # ### end Alembic commands ###
